import { SuppliersModelMongoose } from "../src/dtos/models/suppliers-model";

export async function seedSuppliers() {
  const suppliers = [
    {
      name: "Neoenergia",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Neoenergia.jpg",
      state: "GO",
      costPerKwh: 0.5,
      minKwh: 1000,
      totalClients: 150,
      averageRating: 4,
    },
    {
      name: "Voltalia",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/voltalia_logo.jpeg",
      state: "RJ",
      costPerKwh: 2.3,
      minKwh: 2510,
      totalClients: 200,
      averageRating: 4.5,
    },
    {
      name: "Serena",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Serena.jpg",
      state: "SP",
      costPerKwh: 0.4,
      minKwh: 1575,
      totalClients: 135,
      averageRating: 3.7,
    },
    {
      name: "Enel Green Power",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Enel_Green_Power.jpg",
      state: "TO",
      costPerKwh: 1.4,
      minKwh: 4500,
      totalClients: 420,
      averageRating: 4.3,
    },
    {
      name: "Equinor",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Equinor.jpg",
      state: "SC",
      costPerKwh: 2.7,
      minKwh: 3900,
      totalClients: 239,
      averageRating: 3.9,
    },
    {
      name: "Prime Energy",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Prime_Energy.jpg",
      state: "AL",
      costPerKwh: 4.5,
      minKwh: 3500,
      totalClients: 95,
      averageRating: 2.1,
    },
    {
      name: "Casa dos Ventos",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/casa_dos_ventos.jpg",
      state: "AC",
      costPerKwh: 1.4,
      minKwh: 1500,
      totalClients: 275,
      averageRating: 2.3,
    },
    {
      name: "Ideali Energia",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/Ideali_Energia.png",
      state: "MA",
      costPerKwh: 1.7,
      minKwh: 1200,
      totalClients: 215,
      averageRating: 4.9,
    },
    {
      name: "Luz",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/luz.jpg",
      state: "ES",
      costPerKwh: 2.8,
      minKwh: 900,
      totalClients: 236,
      averageRating: 3.3,
    },
    {
      name: "Topsun",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/topsun.jpeg",
      state: "PB",
      costPerKwh: 1.8,
      minKwh: 1400,
      totalClients: 430,
      averageRating: 3.5,
    },
    {
      name: "Helia Solar",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/helia_solar.jpg",
      state: "CE",
      costPerKwh: 1.3,
      minKwh: 1700,
      totalClients: 580,
      averageRating: 4.7,
    },
    {
      name: "Órigo Energia",
      logo: "https://grzozxo8xlsc.objectstorage.sa-saopaulo-1.oci.customer-oci.com/n/grzozxo8xlsc/b/company-logos/o/origo_energia.jpg",
      state: "SE",
      costPerKwh: 2.7,
      minKwh: 1800,
      totalClients: 90,
      averageRating: 2.5,
    },
  ];

  await SuppliersModelMongoose.insertMany(suppliers);
  console.log("✅ Suppliers inseridos com sucesso!");
}
