export const allSuppliers = [
  {
    id: "1",
    name: "Neoenergia",
    logo: "https://yt3.googleusercontent.com/BX4A8DQyZTmmRSeGf_jKdv8XS-KWZQflaec4Kx9VvCNagE93XuvTb-QJLkBUMB27AawzonRPpw=s160-c-k-c0x00ffffff-no-rj",
    state: "SP",
    costPerKwh: 0.5,
    minKwh: 1000,
    totalClients: 150,
    averageRating: 4,
  },
  {
    id: "2",
    name: "Voltalia",
    logo: "https://yt3.googleusercontent.com/OivMtuSBal_n1ZnW_J8Jb_n3O57lsFDdKtq_E2ID8Aq5Xo1vB3hny2yiZeVNNLd-6xznIsbCNA=s160-c-k-c0x00ffffff-no-rj",
    state: "RJ",
    costPerKwh: 0.4,
    minKwh: 2000,
    totalClients: 200,
    averageRating: 4.5,
  },
  {
    id: "3",
    name: "Serena",
    logo: "https://yt3.googleusercontent.com/GvBTHswPZ0oIM419N0f1k2B3_LBoCv3CyKRsv-T6J0d_yPye_kPApfK1QxtqMgw_o3dBh_94=s160-c-k-c0x00ffffff-no-rj",
    state: "SP",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 3.7,
  },
  {
    id: "4",
    name: "Enel Green Power",
    logo: "https://yt3.googleusercontent.com/ytc/AIdro_mzAwkGl9yZyhIa96U5P8HdyE97Q2NBBZc7WpRwbkIZrQ=s160-c-k-c0x00ffffff-no-rj",
    state: "SP",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 3.7,
  },
  {
    id: "5",
    name: "Equinor",
    logo: "https://yt3.googleusercontent.com/ytc/AIdro_lvPHE12SBXFaTXmnXwkC1Sdz8LFifckjEH6yJrWwzn1Q=s160-c-k-c0x00ffffff-no-rj",
    state: "SP",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 3.7,
  },
  {
    id: "6",
    name: "Prime Energy",
    logo: "https://yt3.googleusercontent.com/kIuFPgZb3kt6BDEe9LXQ09bm4m1688a87nrp3BJTEz5HhPXZCLiIRUNW0ljgxhfIEmCRqAax=s160-c-k-c0x00ffffff-no-rj",
    state: "SP",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 3.7,
  },
  {
    id: "7",
    name: "Start Sol",
    logo: "https://startsolbrasil.com.br/wp-content/uploads/2022/09/logo-startsol2.png",
    state: "AC",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 2.3,
  },
  {
    id: "8",
    name: "Ideali Energia",
    logo: "https://yt3.googleusercontent.com/wpHwTvXWEyzvBY3_SPnq9f_ZaZgt-OOeljP1T5B83-CP1zcPy-VNS4_r5Vr_KMFJ8lyZ05iAqL4=s160-c-k-c0x00ffffff-no-rj",
    state: "AC",
    costPerKwh: 0.4,
    minKwh: 1500,
    totalClients: 135,
    averageRating: 2.3,
  },
];
